server:
  port: 8082
  context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.18.233:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: raven
    password: raven@MySQL
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 118.24.18.233
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
mybatis:
  type-aliases-package: com.raven.demo.entity